# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"

run:
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - govet
    - staticcheck

  exclusions:
    presets:
      - comments
      - std-error-handling
    paths:
      - typescript-go
      - shim

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
