pluginGroup = dev.effect.intellij
pluginId = dev.effect.jetbrains
pluginName = Effect TSGO
pluginRepositoryUrl = https://github.com/Effect-TS/effect-jetbrains-plugin
pluginVersion = 0.1.2

pluginSinceBuild = 262
pluginUntilBuild = 262.*
platformVersion = 262.8665.341
pluginVerifierIntelliJIdeaVersion = 262.9437.22

platformPlugins =
platformBundledPlugins = JavaScript,NodeJS,com.intellij.modules.jcef
platformBundledModules =

gradleVersion = 9.5.1

kotlin.stdlib.default.dependency = false
org.gradle.configuration-cache = true
org.gradle.caching = true
