pluginGroup = dev.effect.intellij
pluginId = dev.effect.jetbrains
pluginName = Effect TSGO
pluginRepositoryUrl = https://github.com/Effect-TS/effect-jetbrains-plugin
pluginVersion = 0.1.6

pluginSinceBuild = 262
pluginUntilBuild = 263.*
platformVersion = 262.10315.144
pluginVerifierWebStormVersion = 263.3889.67
pluginVerifierIntelliJIdeaVersion = 263.3889.65

platformPlugins =
platformBundledPlugins = JavaScript,NodeJS,com.intellij.modules.jcef
platformBundledModules =

gradleVersion = 9.5.1

kotlin.stdlib.default.dependency = false
org.gradle.configuration-cache = true
org.gradle.caching = true
