name: Build

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false

      - name: Fetch sources
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v7
        with:
          name: plugin-distribution
          path: build/distributions/*.zip

  test:
    name: Test (${{ matrix.os }})
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Fetch sources
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: true

      - name: Run checks
        run: ./gradlew check

      - name: Upload test reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v7
        with:
          name: test-reports-${{ matrix.os }}
          path: build/reports/tests

  verify:
    name: Verify Plugin
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false

      - name: Fetch sources
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: true

      - name: Run Plugin Verifier
        run: ./gradlew verifyPlugin

      - name: Upload verifier reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: plugin-verifier-reports
          path: build/reports/pluginVerifier

  qodana:
    name: Qodana
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false

      - name: Fetch sources
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: true

      - name: Run Qodana
        run: ./gradlew qodanaScan --no-configuration-cache --project-cache-dir="$RUNNER_TEMP/qodana-gradle-project-cache"

      - name: Upload Qodana reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: qodana-reports
          path: build/reports/qodana

  releaseDraft:
    name: Release Draft
    if: github.event_name != 'pull_request'
    needs: [build, test, verify, qodana]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Fetch sources
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: true

      - name: Download plugin artifact
        uses: actions/download-artifact@v7
        with:
          name: plugin-distribution
          path: build/distributions

      - name: Remove old release drafts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/{owner}/{repo}/releases \
            --jq '.[] | select(.draft == true) | .id' \
            | xargs -r -I '{}' gh api -X DELETE repos/{owner}/{repo}/releases/{}

      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(./gradlew properties --property version --quiet --console=plain | tail -n 1 | cut -f2- -d ' ')
          RELEASE_NOTE="./build/tmp/release_note.txt"
          ./gradlew getChangelog --project-version "$VERSION" --no-header --quiet --console=plain --output-file="$RELEASE_NOTE"

          gh release create "$VERSION" build/distributions/*.zip \
            --draft \
            --title "$VERSION" \
            --notes-file "$RELEASE_NOTE"
